"""время слов у реплики

Revision ID: 69052433fe21
Revises: bb71fef4d140
Create Date: 2026-09-16 20:37:28.124206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69052433fe21'
down_revision: Union[str, Sequence[str], None] = 'bb71fef4d140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Старые реплики остаются с NULL: звука у них нет, пересчитать время слов
    # не из чего, и делить их по словам просто нельзя.
    op.add_column('segments', sa.Column('words', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'words')
    # ### end Alembic commands ###
