"""Схема на момент переезда с SQLite.

С неё начинается история миграций. Ревизия снята автогенерацией с models.py по
пустой базе — то есть повторяет то, что раньше создавал create_all, и ничего
сверх. Дальше схему меняют только новые ревизии.

Имя файла латиницей намеренно: кириллица в путях переживает не всякий
инструмент, а собранное имя ревизии всё равно читается в докстринге.

Revision ID: bb71fef4d140
Revises: —
Create Date: 07.09.2026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb71fef4d140'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Создаёт схему целиком."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_token_hash'), 'users', ['token_hash'], unique=True)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_audio', sa.Boolean(), nullable=False),
    sa.Column('meeting_mode', sa.String(length=20), nullable=True),
    sa.Column('audio_dir', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_model', sa.String(length=80), nullable=True),
    sa.Column('summary_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_owner_id'), 'meetings', ['owner_id'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_owner_id'), 'speakers', ['owner_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voiceprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('centroid', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_count', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('first_segment_id', sa.Integer(), nullable=False),
    sa.Column('last_segment_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['first_segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Сносит схему целиком: откатывать с самой первой ревизии больше некуда."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    op.drop_table('voiceprints')
    op.drop_table('segments')
    op.drop_index(op.f('ix_speakers_owner_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_meetings_owner_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_users_token_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
